# Generated by Django 4.2.7 on 2023-11-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbas2', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop)
    ]
