# Generated by Django 4.2.7 on 2023-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbas2', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='"USER"',
        ),
    ]
